# Site settings
title: CSE 220
subtitle: Systems Programming
description: This course is an introductory course on computer systems. It introduces computer systems from a programmer's perspective, rather than a system implementer's perspective, which prepares students for more advanced topics that discuss the internals of a computer system (e.g., operating systems or computer architecture). As a result, the focus of the course is teaching programmable interfaces of a computer system as well as how to use them correctly and effectively when writing a program. The topics mainly include hardware/software interfaces (e.g., data representation in memory) and OS/application interfaces (e.g., syscalls). In discussing these topics, the course gives an overview of a complete computer system, the hardware, operating system, compiler, and network, in order to guide students through various components that modern programs rely on to accomplish their intended purposes.
baseurl: "/cse220/" # the subpath of your site, e.g. /blog/
url: "https://droneslab.github.io" # the base hostname & protocol for your site
syllabus: ""
githubdir: "droneslab/cse220"

# Author/user information
email: kdantu@buffalo.edu
twitter_username: dkkarthik
github_username:  dkkarthik
authorurl: "https://cse.buffalo.edu/faculty/kdantu"
address: |
    Computer Science and Engineering
    331 Davis Hall
    Buffalo, NY 14260-2500



# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
